Repository sergiofenoll/project-databases, pull requests merged in 2018-03, with the labels that each got.

#23 10 load sql datadumps
  .travis.yml
  README.md
  requirements.txt
  setup.sh
  sql/create_database.sql
  sql/tables.sql
  sql/user.sql
  src/config.pyc
  src/data_loader.py
  src/default_config.py
  src/project-databases.py
  src/templates/base.html
  src/templates/data-overview.html
  src/templates/dataset-view.html
  src/templates/login-form.html
  src/templates/register-form.html
  src/test_user_data_access.py
  src/user_data_access.py
  src/user_data_access.pyc
Labels: enhancement

#29 24 Unique schemanames
  sql/tables.sql
  src/data_loader.py
Labels: bug

#32 Issue 31 remove users
  app/data_service/models.py
  app/templates/user_service/admin-page.html
  app/templates/user_service/user-data.html
  app/user_service/controllers.py
  app/user_service/models.py
  project_opgave_2018.pdf
  sql/tables.sql
Labels: enhancement

#34 Tables' data is now processed server-side.
  app/__init__.py
  app/api/__init__.py
  app/api/controllers.py
  app/data_service/controllers.py
  app/data_service/models.py
  app/templates/data_service/dataset-view.html
  app/templates/data_service/table-view.html
Labels: modification

#35 Replaced print() statements with calls to built-in logging system
  app/__init__.py
  app/data_service/controllers.py
  app/data_service/models.py
  app/database_connection/models.py
  app/user_service/controllers.py
  app/user_service/models.py
Labels: modification
